app:
  title: Company IDP
  baseUrl: ${IDP_PUBLIC_URL}

backend:
  baseUrl: ${IDP_PUBLIC_URL}
  listen: ':7007'
  trustProxy: true
  reading:
    allow:
      - host: github.com
      - host: raw.githubusercontent.com
  auth:
    keys:
      - secret: ${BACKEND_SECRET}
  cors:
    origin: ${IDP_PUBLIC_URL}
    methods: [GET, HEAD, PATCH, POST, PUT, DELETE]
    credentials: true
  csp:
    connect-src: ["'self'", 'http:', 'https:']
    img-src: ["'self'", 'http:', 'https:', 'data:']
    frame-src: ["'self'", 'https://github.com']
    upgrade-insecure-requests: false
  database:
    client: pg
    connection:
      host: ${POSTGRES_HOST}
      port: ${POSTGRES_PORT}
      user: ${POSTGRES_USER}
      password: ${POSTGRES_PASSWORD}
      database: ${POSTGRES_DB}

integrations:
  github:
    - host: github.com
      token: ${GITHUB_TOKEN}

sonarqube:
  baseUrl: ${SONARQUBE_BASE_URL}
  externalBaseUrl: ${SONARQUBE_EXTERNAL_URL}
  apiKey: ${SONARQUBE_API_KEY}

techdocs:
  builder: local
  generator:
    runIn: local
  publisher:
    type: local

auth:
  environment: production
  providers:
    github:
      production:
        clientId: ${AUTH_GITHUB_CLIENT_ID}
        clientSecret: ${AUTH_GITHUB_CLIENT_SECRET}
        additionalScopes:
          - user:email
        signIn:
          resolvers:
            - resolver: usernameMatchingUserEntityName
            - resolver: emailMatchingUserEntityProfileEmail

catalog:
  orphanStrategy: delete
  import:
    entityFilename: catalog-info.yaml
    pullRequestBranchName: backstage-integration
  rules:
    - allow:
        [
          Component,
          System,
          API,
          Resource,
          Location,
          User,
          Group,
          Domain,
          Template,
        ]
  locations:
    - type: file
      target: ./catalog-info.yaml

    - type: file
      target: ./catalog/org/groups.yaml
      rules:
        - allow: [Group]

    - type: file
      target: ./catalog/org/users.yaml
      rules:
        - allow: [User]

    - type: file
      target: ./catalog/systems.yaml
      rules:
        - allow: [System, Domain]

    - type: file
      target: ./catalog/resources.yaml
      rules:
        - allow: [Resource]

    - type: file
      target: ./catalog/components/reference-services.yaml
      rules:
        - allow: [Component]

    - type: file
      target: ./catalog/templates/nestjs-api/template.yaml
      rules:
        - allow: [Template]

    - type: file
      target: ./catalog/templates/nextjs-fullstack/template.yaml
      rules:
        - allow: [Template]
