apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: company-idp
  title: Company Internal Developer Platform
  description: Internal developer portal for standardized project scaffolding, AWS/SST deployments, and automated security and quality gates.
  tags:
    - backstage
    - idp
    - platform
  annotations:
    github.com/project-slug: Randipa/IDP
spec:
  type: website
  lifecycle: production
  owner: group:default/platform
  system: company-idp
  dependsOn:
    - resource:default/aws-main-account
    - resource:default/github-organization
    - resource:default/sonarqube
