sonar.projectKey=${{ values.name }}
sonar.projectName=${{ values.name }}
sonar.sourceEncoding=UTF-8

sonar.sources=src
sonar.tests=src,test
sonar.exclusions=**/node_modules/**,**/dist/**,**/.sst/**
sonar.test.inclusions=**/*.spec.ts,**/*.e2e-spec.ts
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.qualitygate.wait=true
