---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: randipa
  annotations:
    github.com/user-login: Randipa
spec:
  profile:
    displayName: S.P.Randeepa
    email: saliyapathum711@gmail.com
  memberOf: [platform]
---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: backend-lead
  annotations:
    github.com/user-login: backend-lead
spec:
  profile:
    displayName: Backend Lead
    email: backend-lead@company.com
  memberOf: [backend]
---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: frontend-lead
  annotations:
    github.com/user-login: frontend-lead
spec:
  profile:
    displayName: Frontend Lead
    email: frontend-lead@company.com
  memberOf: [frontend]
