sonar.projectKey=${{ values.name }}
sonar.projectName=${{ values.name }}
sonar.sourceEncoding=UTF-8

sonar.sources=backend/src,packages/client,packages/admin/src
sonar.tests=backend/src,backend/test,packages/client,packages/admin/src
sonar.exclusions=**/node_modules/**,**/dist/**,**/.next/**,**/.sst/**
sonar.test.inclusions=**/*.spec.ts,**/*.test.ts,**/*.e2e-spec.ts
sonar.javascript.lcov.reportPaths=backend/coverage/lcov.info,packages/client/coverage/lcov.info
sonar.qualitygate.wait=true
