---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: backlog
  title: Backlog Web Application
  description: Next.js backlog web app integrated with company IDP
  tags:
    - nextjs
    - aws
    - sst
  annotations:
    github.com/project-slug: Randipa/IDPCatlog
    sonarqube.org/project-key: backlog
    company.io/aws-region: ap-south-1
    company.io/sst-stages: dev,staging,production
spec:
  type: website
  lifecycle: experimental
  owner: group:default/frontend
  system: client-delivery
